version: '3'
services:
    web:
        build: 
            context: .
            dockerfile: ./containers/web/Dockerfile
        ports:
            - 3000:3000
            # volumesでマウントしておかないとvscodeで作成したファイルとかをdockerのLinux側にコピーしてくれないので必ず書く
        volumes:
            - .:/usr/src/app
            # node_modulesはWindowsはWindows、LinuxはLinuxで内容が異なるのでコピーしたくないといった設定
            - /usr/src/app/node_modules
    # db:
    #     build:
    #         context: .
    #         dockerfile: ./containers/db/Dockerfile
    #     ports:
    #         - 5433:5432
    #     environment:
    #         POSTGRES_USER: admin
    #         POSTGRES_PASSWORD: admin